#!/bin/sh
#-
# SPDX-License-Identifier: BSD-2-Clause
#
# Copyright (c) 2025 The FreeBSD Foundation
#
# This software was developed by Alfonso Sabato Siciliano
# under sponsorship from the FreeBSD Foundation.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
# OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
# HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
# LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
# OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
# SUCH DAMAGE.
#

readonly BSDDIALOG_OK=0
readonly BSDDIALOG_YES=$BSDDIALOG_OK

###
# 1. Yes-No question to install KDE.
# 2. Radiolist GPU drivers, default item based on the output of fwget -n -q.
# 3. Installation progress: GPU driver, Xorg, KDE, and conf.
# 4. Checklist to select users to add to the video group.
###

# SECTION 1
bsddialog --backtitle "FreeBSD Installer" --title "Desktop" --colors \
	--yesno "FreeBSD provides a variety of graphical environments that can be easily installed through ports and packages. Refer to the FreeBSD Handbook available at \Zuhttps://docs.freebsd.org\Zn.\n\nWould you like to install KDE Plasma now and start it at the next system reboot? Please note this is an experimental feature." 0 0
[ $? -ne $BSDDIALOG_YES ] && exit 1

# SECTION 2: Graphic card
PKGGPU=`fwget -n -q | grep gpu`
BOOTMETHOD=`sysctl -n machdep.bootmethod`
# F1 help message
HELPGPU="System firmware boot method: $BOOTMETHOD

GPU:
`pciconf -lv | grep -A 4 vga`

Detected firmware package: $PKGGPU"
# end F1 help message

gpu=$(bsddialog --backtitle "FreeBSD Installer" --title "Desktop" \
	--ok-label Install --cancel-label Skip \
	--hmsg  "$HELPGPU" --item-depth \
	--radiolist "F1 to know your GPU, SPACE to select a driver:" 0 0 0 \
	0 DRM           "Intel and AMD Metaport"                         off \
	1 Intel         "Intel APUs starting with HD3000 / Sandy Bridge" off \
	1 AMD           "AMD GPUs starting with HD7000 / Tahiti"         off \
	1 Radeon        "Older AMD GPUs (EFI boot should be disabled)"   off \
	0 NVIDIA        "Proprietary driver "                            off \
	1 Optimus-Intel "Nvidia Optimus and Intel GPU"                   off \
	1 Optimus-AMD   "Nvidia Optimus and AMD GPU"                     off \
	0 VESA          "GPU not supported by other drivers (BIOS)"      off \
	0 SCFB          "GPU not supported by other drivers (UEFI)"      off \
	3>&1 1>&2 2>&3 3>&-)
[ $? -ne $BSDDIALOG_OK ] && exit 1
[ -z $gpu ] && exit 0

toinstall=""
postconfig=""

case $gpu in
	DRM )
		toinstall="$toinstall graphics/drm-kmod"
		postconfig="sysrc kld_list+=\" i915kms amdgpu radeonkms\""
		;;
	Optimus-Intel)
		optimus=1
		;&
	Intel)
		toinstall="$toinstall graphics/drm-kmod x11-drivers/xf86-video-intel"
		postconfig="sysrc kld_list+=\" i915kms\""
		;;
	Optimus-AMD)
		optimus=1
		;&
	AMD)
		toinstall="$toinstall graphics/drm-kmod"
		postconfig="sysrc kld_list+=\" amdgpu\""
		;;
	Radeon )
		toinstall="$toinstall graphics/drm-kmod"
		postconfig="sysrc kld_list+=\" radeonkms\""
		;;
	VESA)
		toinstall="$toinstall x11-drivers/xf86-video-vesa"
		postconfig="echo -e \"Section \\\"Device\\\"\n\tIdentifier \\\"Card0\\\"\n\tDriver \\\"vesa\\\"\nEndSection\" >> $XDRIVERFILE"
		;;
	SCFB)
		toinstall="$toinstall x11-drivers/xf86-video-scfb"
		postconfig="echo -e \"Section \\\"Device\\\"\n\tIdentifier \\\"Card0\\\"\n\tDriver \\\"scfb\\\"\nEndSection\" >> $XDRIVERFILE"
		;;
esac

if [ $gpu = NVIDIA -o $optimus ]; then
	items='Untested NVIDIA-550 "Proprietary driver version 550" off'
	if [ $optimus ]; then
		items="$items "'"" NVIDIA-390 "Proprietary driver version 390" off'
	else
		items="$items "'Untested NVIDIA-470 "Proprietary driver version 470" off'
		items="$items "'"" NVIDIA-390 "Proprietary driver version 390" off'
		items="$items "'Untested NVIDIA-340 "Proprietary driver version 340 (only PORT)" off'
		items="$items "'Untested NVIDIA-304 "Proprietary driver version 304 (only PORT)" off'
	fi
	gpu=$(echo $items | xargs -o bsddialog --title "$TITLE" \
		--ok-label Install --cancel-label Skip --hmsg "$HELPGPU" \
		--item-prefix \
		--radiolist "F1 to know your GPU, SPACE to select a driver:" \
		0 0 0 \
	3>&1 1>&2 2>&3 3>&-)
	if [ $? -eq $BSDDIALOG_OK -a -n "$gpu" ]; then
		version=${gpu##NVIDIA-}
		if [ $version -eq 550 ]; then
			toinstall="$toinstall x11/nvidia-driver"
			if [ $optimus ]; then
				toinstall="$toinstall x11/nvidia-hybrid-graphics"
			fi
		else
			toinstall="$toinstall x11/nvidia-driver-$version"
			if [ $optimus ]; then
				toinstall="$toinstall x11/nvidia-hybrid-graphics-390"
			fi
		fi
		if [ $version -le 340 ]; then
			if [ $INSTALLFUNC = install_pkgs ]; then
				$DIALOG --title "${TITLE}" --ok-label Quit \
					--msgbox "The driver nvidia-driver-$version can be installed only via PORTS, restart $0 with -P option." 0 0
				log "Cannot install nvidia-driver-$version via pkg, restart $0 with -P option"
				exit $EXIT_FAILURE
			fi
			postconfig="sysrc kld_list+=\" nvidia\""
		else
			postconfig="$postconfig ; sysrc kld_list+=\" nvidia-modeset\""
		fi
	fi
fi

# SECTION 3: Installation
bsddialog --sleep 5 --backtitle "FreeBSD Installer" --title "Desktop" \
	--mixedgauge "\nInstallation 450/512 kscreen\n" 0 0 40 \
	"" " -9" \
	"GPU driver" " -6" \
	"KDE installation" 35 \
	"Configuration"	" -11 "

# TODO: add installation and configuration progress bars

# SECTION 4: Video group
[ $gpu = VESA -o $gpu = SCFB ] && exit 0

users=`pw usershow -a | awk -F":" '$10 != "" && $10 != "/usr/sbin/nologin"{print $1 " \""$8"\" off"}' | sort`

exec 5>&1
USERS=$(echo ${users} | xargs -o bsddialog --backtitle "FreeBSD Installer" \
	--title "Desktop" --ok-label Continue --cancel-label Skip \
	--checklist 'Select users to add to the "video" group for 3D acceleration.' 0 0 0 2>&1 1>&5)
exec 5>&-

# TODO: add pw add to video group
